### ISSUE TITLE
End button text change

### ISSUE THREAD

**Issue by danish1023** [mohanasundaramn/ms-flutter-packages#1]
How can I change last slide button text to "Done" instead of "Next" ?

**Comment by mohanasundaramn** [comment]
@danish1023 thanks for raising an issue, this is a known bug if you override the default `nextButton` as of now there is no way to change text name. I am working on some API changes. Will release a new version soon.

**Comment by mohanasundaramn** [comment]
@danish1023  Bug Fixed, check [`v 0.0.2+1` ](https://pub.dev/packages/flutter_onboard) or [example](https://github.com/mohanasundaramn/ms-flutter-packages/tree/master/flutter_onboard/example) for more info. If you find any bug feel free to raise an issue.
