### ISSUE TITLE
flutter_onboard incompatible with provider 6.0.0

### ISSUE THREAD

**Issue by oscardelgado** [mohanasundaramn/ms-flutter-packages#11]
If I use this library, i must keep provider: ^5.0.0 
It's not compatible with version 6. 
It would be great to solve this.

**Comment by mohanasundaramn** [comment]
@oscardelgado [`V1.0.4`](https://pub.dev/packages/flutter_onboard/changelog) is published.

**Comment by oscardelgado** [comment]
Thanks!
